[theme]
primaryColor = "#0C6EFD"        # Professional-looking blue
backgroundColor = "#FFFFFF"     # White background
secondaryBackgroundColor = "#F0F2F6" # Light grey background
textColor = "#000000"           # Black text
font = "sans serif"             # Clean font

[server]
headless = true
